# Cluster Security Groups
  - name: Create cluster SSH for remote access (cidr)
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 22
      end_port: 22
      cidr: 0.0.0.0/0
    tags: sgr

  - name: Create cluster SSH for remote access
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 22
      end_port: 22
      user_security_group: "{{ item }}"
    with_items: "{{ cluster_ssh_group_names }}"
    tags: sgr

# Heketi API
  - name: Create heketi API 8080 TCP (cidr)
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 8080
      end_port: 8080
      cidr: 0.0.0.0/0
    tags: sgr

  - name: Create heketi API 8080 TCP
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 8080
      end_port: 8080
      user_security_group: "{{ item }}"
    with_items: "{{ cluster_service_group_names }}"
    tags: sgr

# GlusterFs ports
  - name: Create rpcbind 111 TCP/UDP rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 111
      end_port: 111
      protocol: tcp
      user_security_group: "{{ cluster_security_group_name}}"
    tags: sgr

  - name: Create rpcbind 111 TCP/UDP rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 111
      end_port: 111
      protocol: udp
      user_security_group: "{{ cluster_security_group_name}}"
    tags: sgr

  - name: Create NFS 2049 TCP rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 2049
      end_port: 2049
      user_security_group: "{{ cluster_security_group_name}}"
    tags: sgr

  - name: Create NFS Services 38465:38469 TCP rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 38465
      end_port: 38469
      user_security_group: "{{ cluster_security_group_name}}"
    tags: sgr

  - name: Create Gluster Server 24007 TCP rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 24007
      end_port: 24007
      user_security_group: "{{ cluster_security_group_name}}"
    tags: sgr

  - name: Create Brick Protocal 49152 TCP rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ cluster_security_group_name}}"
      start_port: 49152
      end_port: 49152
      user_security_group: "{{ cluster_security_group_name}}"
    tags: sgr
